// flow-typed signature: a43a4bc18b0c51444093da36b551bd34
// flow-typed version: <<STUB>>/next-redux-saga_v1.0.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-redux-saga/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-redux-saga/dist/index.js' {
  declare module.exports: $Exports<'next-redux-saga/dist/index'>;
}
