// flow-typed signature: 8f5001e60b37b37fcff56650f0125c2f
// flow-typed version: <<STUB>>/normalize.css_v^8.0.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
