// flow-typed signature: 4d4711ed49835411987876773545b3a9
// flow-typed version: <<STUB>>/@babel/preset-es2015_v^7.0.0-beta.53/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-es2015'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-es2015' {
  declare module.exports: any;
}
